language: python
python:
  - 3.6
  - 3.7
  - 3.8
  - 3.9
  - 3.10
before_install:
  - python --version
  - pip install -U pip
  - pip install -r requirements.txt
  - pip install codecov requests-mock
install:
  - pip install .
script:
  - coverage run -m unittest
notifications:
  email: false
after_success:
  - codecov
