language: python
python:
  - 3.4
  - 3.5
  - 3.6
before_install:
  - python --version
  - pip install -U pip
  - pip install -r requirements.txt
install:  
  - pip install .
script:
  - python tests/tests.py
notifications:
  email: false