language: python
python:
  - 3.4 
before_install:
  - python --version
  - pip install -U pip
  - pip install -r requirements.txt
  - pip install --user codecov
install:  
  - pip install .
script:
  - coverage run tests/tests.py
notifications:
  email: false
after_success:
  - codecov